use_frameworks!

platform :ios, '9.0'

target 'AFNetworking_Example' do
  pod 'AFNetworking', :path => '../'

  target 'AFNetworking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
